#!/usr/bin/env python3
"""prescription_enforcer.py — Close the prescription gap (L-601, L-1300).
72% of rule-bearing lessons are ASPIRATIONAL. Ranks actionable prescriptions
by Sharpe+wirability, generates periodic/gate enforcement entries.
Usage: python3 tools/prescription_enforcer.py [--top N] [--dry-run] [--apply] [--json]
"""
import argparse, json, re, sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(REPO_ROOT / "tools"))
try:
    from enforcement_router import scan_lessons, build_reference_maps, classify
except ImportError:
    print("FAIL: cannot import enforcement_router.py", file=sys.stderr); sys.exit(1)

PERIODICS_PATH = REPO_ROOT / "tools" / "periodics.json"
_PERIODIC_KW = ["audit", "scan", "check", "measure", "review", "monitor", "track",
                 "run python3", "run `python3", "cadence", "every", "periodic"]
_GATE_KW = ["pre-commit", "check.sh", "gate", "block", "abort", "fail if",
            "never commit", "reject", "validate before"]
_TOOL_KW = ["wire into", "add to", "integrate", "extend", "hook into",
            "output from", "pipe to", "feed into"]


def _classify_enforcement(rule: str) -> str:
    lo = rule.lower()
    g = sum(1 for s in _GATE_KW if s in lo)
    p = sum(1 for s in _PERIODIC_KW if s in lo)
    t = sum(1 for s in _TOOL_KW if s in lo)
    if g > p and g > t: return "check_gate"
    if t > p: return "tool_integration"
    return "periodic"


def _tool_target(rule: str) -> str | None:
    m = re.search(r"(tools/[\w_]+\.(?:py|sh))", rule)
    return m.group(1) if m else None


def _make_periodic(lesson: dict, session: str = "S500") -> dict:
    lid, rule, tool = lesson["lesson"], lesson["rule"], _tool_target(lesson["rule"])
    desc = f"Enforce {lid}: {rule[:120].rstrip('.')}. Auto-generated by prescription_enforcer.py."
    if tool:
        desc = f"Run `python3 {tool}` — enforces {lid}: {rule[:100].rstrip('.')}."
    return {"id": f"enforce-{lid.lower()}", "description": desc, "cadence_sessions": 15,
            "last_reviewed_session": session, "registered_by": session, "last_session": session,
            "note": f"Auto-generated for {lid} (Sharpe={lesson['sharpe']}). Rule: {rule[:80]}"}


def _rank(lessons_dir: Path) -> list[dict]:
    rules = scan_lessons(lessons_dir, min_sharpe=0)
    s_refs, p_refs = build_reference_maps(REPO_ROOT)
    out = []
    for r in rules:
        if classify(r["lesson"], s_refs, p_refs) != "ASPIRATIONAL" or not r["actionable"]:
            continue
        w = r["wirability"]["score"]
        priority = round(r["sharpe"] * (1.0 + w / 3.0), 2)
        out.append({**r, "enforcement_type": _classify_enforcement(r["rule"]),
                    "tool_target": _tool_target(r["rule"]), "priority_score": priority})
    out.sort(key=lambda x: (-x["priority_score"], -x["sharpe"]))
    return out


def _load_periodics() -> list[dict]:
    try: return json.loads(PERIODICS_PATH.read_text(encoding="utf-8"))["items"]
    except Exception: return []


def _save_periodics(items: list[dict]) -> None:
    PERIODICS_PATH.write_text(json.dumps({"items": items}, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--top", type=int, default=10)
    ap.add_argument("--dry-run", action="store_true", default=True)
    ap.add_argument("--apply", action="store_true", help="Add periodic entries to periodics.json")
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--min-sharpe", type=int, default=5)
    args = ap.parse_args()
    if args.apply: args.dry_run = False

    candidates = [c for c in _rank(REPO_ROOT / "memory" / "lessons") if c["sharpe"] >= args.min_sharpe]
    top = candidates[:args.top]
    existing = {p["id"] for p in _load_periodics()}

    recs = []
    for c in top:
        etype, exists = c["enforcement_type"], f"enforce-{c['lesson'].lower()}" in existing
        rec = {"lesson": c["lesson"], "sharpe": c["sharpe"], "domain": c["domain"],
               "priority_score": c["priority_score"], "rule_summary": c["rule"][:100],
               "enforcement_type": etype, "tool_target": c["tool_target"],
               "wirability_score": c["wirability"]["score"], "already_exists": exists}
        if etype == "periodic":
            rec["periodic_entry"] = _make_periodic(c)
        elif etype == "check_gate":
            rec["gate_snippet"] = (f"# {c['lesson']} enforcement (Sharpe={c['sharpe']}): "
                                   f"{c['rule'][:80]}\n# TODO: add structural gate for {c['lesson']}")
        else:
            rec["integration_note"] = f"Wire {c['lesson']} into {c['tool_target'] or 'target tool'}"
        recs.append(rec)

    if args.json:
        print(json.dumps({"total_actionable_aspirational": len(candidates), "showing": len(top),
                          "mode": "apply" if args.apply else "dry-run", "recommendations": recs}, indent=2))
        return

    print(f"=== PRESCRIPTION ENFORCER (L-601/L-1300) ===")
    print(f"Actionable aspirational (Sharpe>={args.min_sharpe}): {len(candidates)}")
    print(f"Showing top {len(top)} by priority score:\n")
    for i, r in enumerate(recs, 1):
        tag = " [EXISTS]" if r["already_exists"] else ""
        print(f"{i}. {r['lesson']} (Sh={r['sharpe']}, W{r['wirability_score']}/3, "
              f"pri={r['priority_score']}){tag}")
        print(f"   {r['domain']} | {r['enforcement_type']}" +
              (f" | {r['tool_target']}" if r.get("tool_target") else ""))
        print(f"   {r['rule_summary']}")
        if r["enforcement_type"] == "periodic" and not r["already_exists"]:
            print(f"   -> {r['periodic_entry']['id']} (cadence {r['periodic_entry']['cadence_sessions']}s)")
        elif r["enforcement_type"] == "check_gate":
            print(f"   -> check.sh gate (manual wiring needed)")
        print()

    if args.apply:
        items, applied = _load_periodics(), 0
        for r in recs:
            if r["enforcement_type"] == "periodic" and not r["already_exists"]:
                items.append(r["periodic_entry"]); applied += 1
                print(f"  APPLIED: {r['periodic_entry']['id']}")
        if applied:
            _save_periodics(items)
            print(f"\nAdded {applied} periodic entries to {PERIODICS_PATH}")
        else:
            print("\nNo new entries to add.")
    else:
        n = sum(1 for r in recs if r["enforcement_type"] == "periodic" and not r["already_exists"])
        if n: print(f"Dry-run: {n} periodic entries would be added. Use --apply to write.")


if __name__ == "__main__":
    main()
