#!/usr/bin/env python3
"""
Classify Cites: headers in lesson files as 'organic' (hand-written) or 'auto'
(generated by tools/lesson_quality_fixer.py).

Ground truth:
  - lesson_quality_fixer.py was created at S357, mass --fix harvest ran at S358
    (commit 7aa43637, 174 lessons received auto-generated Cites: headers)
  - No subsequent mass harvest was run

Heuristic classification:
  1. Known S358 harvest victim (from git diff) -> auto_confirmed
  2. Session < S358 AND not in S358 harvest -> organic (predates fixer, hand-written)
  3. Session >= S358 AND Cites refs NOT all in body -> organic (author cited external work)
  4. Session >= S358 AND Cites refs all subset of body refs -> auto (fixer pattern)
  5. No session header -> use lesson ID heuristic + body-ref subset test
  6. Non-lesson refs only (P-/F-/ISO-) in Cites: -> organic (fixer only adds L-NNN)

Cross-domain analysis: for organic citations, resolve Domain: headers of cited
lessons and check whether the citation graph spans multiple domains.
"""

import json
import os
import re
import subprocess
import sys
from collections import Counter, defaultdict
from pathlib import Path

REPO_ROOT = Path("/mnt/c/Users/canac/REPOSITORIES/swarm")
LESSONS_DIR = REPO_ROOT / "memory" / "lessons"

# Ground truth: lessons modified in S358 harvest commit
S358_HARVEST_COMMIT = "7aa43637"
FIXER_DEPLOY_SESSION = 358


def get_s358_harvest_lessons() -> set:
    """Get list of lesson IDs modified in the S358 harvest commit."""
    try:
        result = subprocess.run(
            ["git", "show", S358_HARVEST_COMMIT, "--stat"],
            capture_output=True, text=True, cwd=str(REPO_ROOT)
        )
        harvest_ids = set()
        for line in result.stdout.splitlines():
            m = re.search(r"memory/lessons/(L-\d+)\.md", line)
            if m:
                harvest_ids.add(m.group(1))
        return harvest_ids
    except Exception as e:
        print(f"WARNING: Could not read S358 harvest commit: {e}", file=sys.stderr)
        return set()


def parse_lesson(path: Path) -> dict:
    """Parse a lesson file, extracting headers and body refs."""
    try:
        content = path.read_text(encoding="utf-8", errors="replace")
    except Exception:
        return None

    result = {"id": path.stem, "path": str(path)}

    # Session number (handles both "Session: S123" and "Session: 123")
    sess_match = re.search(r"Session:\s*S?(\d+)", content)
    result["session"] = int(sess_match.group(1)) if sess_match else None

    # Domain
    domain_match = re.search(r"Domain:\s*(.+?)(?:\s*\||\s*$)", content, re.MULTILINE)
    result["domain"] = domain_match.group(1).strip() if domain_match else None

    # Cites: header line
    cites_match = re.search(r"^Cites:\s*(.+)", content, re.MULTILINE)
    result["cites_raw"] = cites_match.group(1).strip() if cites_match else None

    if result["cites_raw"]:
        # Extract all L-NNN references from the Cites: header
        result["cites_lesson_refs"] = set(re.findall(r"L-(\d+)", result["cites_raw"]))
        # Also extract non-lesson refs (P-NNN, F-XXX, ISO-NNN, PHIL-NNN, B-NNN etc.)
        result["cites_all_refs"] = set(re.findall(r"[A-Z][\w-]*\d+", result["cites_raw"]))
    else:
        result["cites_lesson_refs"] = set()
        result["cites_all_refs"] = set()

    # Find the Cites: line position to split header from body
    lines = content.splitlines()
    cites_line_idx = None
    for i, line in enumerate(lines):
        if line.startswith("Cites:"):
            cites_line_idx = i
            break

    # Body = everything EXCEPT the title line and the Cites: header line
    body_content = ""
    for i, line in enumerate(lines):
        # Skip the title line (# L-NNN: ...)
        if i == 0:
            continue
        # Skip the Cites: header line
        if cites_line_idx is not None and i == cites_line_idx:
            continue
        body_content += line + "\n"

    # Extract L-NNN refs from body (excluding title and Cites: line)
    raw_body_refs = set(re.findall(r"\bL-(\d+)\b", body_content))
    # Remove self-reference
    own_num = re.search(r"\d+", result["id"])
    if own_num:
        raw_body_refs.discard(own_num.group())
    result["body_lesson_refs"] = raw_body_refs

    return result


def classify_lesson(lesson: dict, harvest_ids: set) -> dict:
    """Classify a lesson's Cites: header as organic or auto.

    Returns None if lesson has no Cites: header.
    """
    if not lesson["cites_raw"]:
        return None

    classification = {
        "id": lesson["id"],
        "session": lesson["session"],
        "domain": lesson["domain"],
        "cites_raw": lesson["cites_raw"],
        "cites_lesson_refs": sorted(lesson["cites_lesson_refs"], key=lambda x: int(x)),
        "body_lesson_refs": sorted(lesson["body_lesson_refs"], key=lambda x: int(x)),
    }

    cites_l_refs = lesson["cites_lesson_refs"]
    body_l_refs = lesson["body_lesson_refs"]

    # ---- Ground truth check: was this lesson in the S358 harvest? ----
    in_harvest = lesson["id"] in harvest_ids

    # ---- Classification rules (ordered by confidence) ----

    # Rule 1: Known S358 harvest victim -> auto_confirmed
    # The fixer adds Cites: by extracting body L-NNN refs. If the lesson was in the
    # harvest AND the Cites: refs are a subset of body refs, it's definitively auto.
    # But: if someone later hand-edited the Cites: to add refs not in body, the
    # harvest was overwritten -> organic
    if in_harvest:
        cites_only = cites_l_refs - body_l_refs
        if cites_only:
            # Harvest added it, but it was later hand-edited to add external refs
            classification["class"] = "organic"
            classification["reason"] = f"s358_harvest_then_hand_edited (extra: {sorted(cites_only, key=lambda x: int(x))})"
            classification["in_s358_harvest"] = True
            return classification
        else:
            classification["class"] = "auto"
            classification["reason"] = "s358_harvest_confirmed"
            classification["in_s358_harvest"] = True
            return classification

    # Rule 2: Pre-S358 session AND not in harvest -> organic (predates fixer)
    if lesson["session"] is not None and lesson["session"] < FIXER_DEPLOY_SESSION:
        classification["class"] = "organic"
        classification["reason"] = f"pre-S358 (S{lesson['session']})"
        classification["in_s358_harvest"] = False
        return classification

    # Rule 3: No session header -> heuristic based on content analysis
    if lesson["session"] is None:
        classification["in_s358_harvest"] = False
        # Edge case: Cites: has no L-refs (only P-NNN, F-XXX, ISO-NNN, etc.)
        if not cites_l_refs:
            classification["class"] = "organic"
            classification["reason"] = "no_session_non_lesson_refs_only"
            return classification
        # Check if Cites: refs are all in body (auto pattern)
        cites_only = cites_l_refs - body_l_refs
        if cites_only:
            classification["class"] = "organic"
            classification["reason"] = f"no_session_cites_not_in_body: {sorted(cites_only, key=lambda x: int(x))}"
            return classification
        # All cites in body -> likely auto (but uncertain without session info)
        classification["class"] = "auto"
        classification["reason"] = "no_session_all_cites_in_body"
        return classification

    # Rule 4: Post-S358 session, not in harvest
    classification["in_s358_harvest"] = False

    # Edge case: Cites: has no L-refs (only P-NNN, F-XXX, ISO-NNN, etc.)
    if not cites_l_refs and lesson["cites_raw"]:
        classification["class"] = "organic"
        classification["reason"] = "non_lesson_refs_only"
        return classification

    # Check if Cites: refs are all in body (auto pattern) or not
    cites_only = cites_l_refs - body_l_refs
    if cites_only:
        classification["class"] = "organic"
        classification["reason"] = f"cites_not_in_body: {sorted(cites_only, key=lambda x: int(x))}"
        return classification

    # All Cites: L-refs are in the body -> auto pattern
    if cites_l_refs and cites_l_refs.issubset(body_l_refs):
        classification["class"] = "auto"
        classification["reason"] = "post_s358_all_cites_in_body"
        return classification

    # Fallback
    classification["class"] = "auto"
    classification["reason"] = "fallback_empty"
    return classification


def main():
    # Get ground truth from git
    print("[1/5] Loading S358 harvest ground truth from git...", file=sys.stderr)
    harvest_ids = get_s358_harvest_lessons()
    print(f"  S358 harvest modified {len(harvest_ids)} lesson files", file=sys.stderr)

    # Load all lessons
    print("[2/5] Loading all lessons...", file=sys.stderr)
    lessons = {}
    for path in sorted(LESSONS_DIR.glob("L-*.md")):
        lesson = parse_lesson(path)
        if lesson:
            lessons[lesson["id"]] = lesson

    total_lessons = len(lessons)
    print(f"  Loaded {total_lessons} lessons", file=sys.stderr)

    # Build domain lookup for cross-domain analysis
    domain_lookup = {}
    for lid, lesson in lessons.items():
        domain_lookup[lid] = lesson["domain"]

    # Classify each lesson with Cites: header
    print("[3/5] Classifying Cites: headers...", file=sys.stderr)
    classifications = []
    for lid, lesson in sorted(lessons.items(), key=lambda x: x[0]):
        c = classify_lesson(lesson, harvest_ids)
        if c:
            classifications.append(c)

    total_with_cites = len(classifications)
    organic = [c for c in classifications if c["class"] == "organic"]
    auto = [c for c in classifications if c["class"] == "auto"]

    # Reason breakdown
    organic_reason_counts = Counter()
    auto_reason_counts = Counter()
    for c in organic:
        key = c["reason"].split(":")[0].split("(")[0].strip()
        organic_reason_counts[key] += 1
    for c in auto:
        key = c["reason"]
        auto_reason_counts[key] += 1

    # Cross-domain analysis for organic citations
    print("[4/5] Analyzing cross-domain organic citations...", file=sys.stderr)
    organic_cross_domain = []
    for c in organic:
        own_domain = c["domain"]
        cited_domains = set()

        # Get domains of all cited lessons
        for ref_num in c["cites_lesson_refs"]:
            # Try different zero-padding formats
            for fmt in [f"L-{ref_num}", f"L-{ref_num.zfill(3)}"]:
                if fmt in domain_lookup and domain_lookup[fmt]:
                    domains = [d.strip().lower() for d in domain_lookup[fmt].split(",")]
                    cited_domains.update(domains)

        # Parse own domain
        if own_domain:
            own_domains = set(d.strip().lower() for d in own_domain.split(","))
        else:
            own_domains = set()

        all_domains = own_domains | cited_domains
        # Cross-domain = cited lessons bring in domains NOT already in the citing lesson
        is_cross_domain = len(all_domains) >= 2 and cited_domains and not cited_domains.issubset(own_domains)

        c["own_domains"] = sorted(own_domains)
        c["cited_domains"] = sorted(cited_domains)
        c["all_domains_in_graph"] = sorted(all_domains)
        c["is_cross_domain"] = is_cross_domain

        if is_cross_domain:
            organic_cross_domain.append(c)

    # Also mark auto lessons for completeness
    for c in auto:
        c["is_cross_domain"] = False
        c["own_domains"] = []
        c["cited_domains"] = []
        c["all_domains_in_graph"] = []

    # Session distribution
    organic_sessions = [c["session"] for c in organic if c["session"] is not None]
    auto_sessions = [c["session"] for c in auto if c["session"] is not None]

    # Ground truth validation: how many S358 harvest lessons still have auto-pattern Cites?
    harvest_in_corpus = [c for c in classifications if c.get("in_s358_harvest")]
    harvest_still_auto = [c for c in harvest_in_corpus if c["class"] == "auto"]
    harvest_now_organic = [c for c in harvest_in_corpus if c["class"] == "organic"]

    print("[5/5] Building output...", file=sys.stderr)

    # Build output
    output = {
        "metadata": {
            "description": "Classification of Cites: headers as organic (hand-written) vs auto (lesson_quality_fixer.py)",
            "heuristics": [
                "S358 harvest ground truth from git diff (commit 7aa43637)",
                "Pre-S358 session + not in harvest -> organic (predates fixer)",
                "Post-S358 + Cites L-refs NOT all in body -> organic (author cited external work)",
                "Post-S358 + Cites L-refs all in body -> auto (fixer pattern)",
                "No session header -> body-ref subset test as tiebreaker",
                "Non-lesson refs only (P-/F-/ISO-) -> organic (fixer only adds L-NNN)",
            ],
            "fixer_deploy_session": FIXER_DEPLOY_SESSION,
            "s358_harvest_commit": S358_HARVEST_COMMIT,
            "date": "2026-03-02",
            "total_lessons_in_corpus": total_lessons,
        },
        "summary": {
            "total_with_cites": total_with_cites,
            "total_with_cites_pct_of_corpus": round(total_with_cites / total_lessons * 100, 1),
            "organic_count": len(organic),
            "organic_pct": round(len(organic) / total_with_cites * 100, 1) if total_with_cites else 0,
            "auto_count": len(auto),
            "auto_pct": round(len(auto) / total_with_cites * 100, 1) if total_with_cites else 0,
            "organic_cross_domain_count": len(organic_cross_domain),
            "organic_cross_domain_rate_of_organic": round(
                len(organic_cross_domain) / len(organic) * 100, 1
            ) if organic else 0,
            "organic_cross_domain_rate_of_total_lessons": round(
                len(organic_cross_domain) / total_lessons * 100, 1
            ) if total_lessons else 0,
        },
        "ground_truth_validation": {
            "s358_harvest_lessons_in_git": len(harvest_ids),
            "s358_harvest_lessons_with_cites_now": len(harvest_in_corpus),
            "still_auto_pattern": len(harvest_still_auto),
            "hand_edited_since": len(harvest_now_organic),
            "hand_edited_examples": [
                {"id": c["id"], "reason": c["reason"]}
                for c in harvest_now_organic[:10]
            ],
        },
        "organic_reasons": dict(organic_reason_counts.most_common()),
        "auto_reasons": dict(auto_reason_counts.most_common()),
        "session_distribution": {
            "organic_min_session": min(organic_sessions) if organic_sessions else None,
            "organic_max_session": max(organic_sessions) if organic_sessions else None,
            "organic_mean_session": round(sum(organic_sessions) / len(organic_sessions), 1) if organic_sessions else None,
            "organic_median_session": sorted(organic_sessions)[len(organic_sessions)//2] if organic_sessions else None,
            "auto_min_session": min(auto_sessions) if auto_sessions else None,
            "auto_max_session": max(auto_sessions) if auto_sessions else None,
            "auto_mean_session": round(sum(auto_sessions) / len(auto_sessions), 1) if auto_sessions else None,
        },
        "classifications": classifications,
        "organic_cross_domain_details": [
            {
                "id": c["id"],
                "session": c["session"],
                "own_domains": c["own_domains"],
                "cited_domains": c["cited_domains"],
                "all_domains": c["all_domains_in_graph"],
                "cites_lesson_refs": c["cites_lesson_refs"],
            }
            for c in organic_cross_domain
        ],
    }

    # Print summary to stderr
    print("\n" + "=" * 60, file=sys.stderr)
    print("  CITES CLASSIFICATION RESULTS", file=sys.stderr)
    print("=" * 60, file=sys.stderr)
    print(f"\nCorpus: {total_lessons} lessons", file=sys.stderr)
    print(f"Lessons with Cites: headers: {total_with_cites} ({output['summary']['total_with_cites_pct_of_corpus']}% of corpus)", file=sys.stderr)
    print(f"\n--- Classification ---", file=sys.stderr)
    print(f"  Organic (hand-written): {len(organic)} ({output['summary']['organic_pct']}%)", file=sys.stderr)
    print(f"  Auto (fixer-generated): {len(auto)} ({output['summary']['auto_pct']}%)", file=sys.stderr)
    print(f"\n--- Organic reason breakdown ---", file=sys.stderr)
    for reason, count in organic_reason_counts.most_common():
        print(f"  {reason}: {count}", file=sys.stderr)
    print(f"\n--- Auto reason breakdown ---", file=sys.stderr)
    for reason, count in auto_reason_counts.most_common():
        print(f"  {reason}: {count}", file=sys.stderr)
    print(f"\n--- Ground truth validation (S358 harvest) ---", file=sys.stderr)
    print(f"  Lessons in S358 harvest commit: {len(harvest_ids)}", file=sys.stderr)
    print(f"  Still have auto-pattern Cites: {len(harvest_still_auto)}", file=sys.stderr)
    print(f"  Hand-edited since harvest: {len(harvest_now_organic)}", file=sys.stderr)
    print(f"\n--- Cross-domain organic citations ---", file=sys.stderr)
    print(f"  Organic lessons with cross-domain Cites: {len(organic_cross_domain)}", file=sys.stderr)
    print(f"  Rate among organic: {output['summary']['organic_cross_domain_rate_of_organic']}%", file=sys.stderr)
    print(f"  Rate of total corpus: {output['summary']['organic_cross_domain_rate_of_total_lessons']}%", file=sys.stderr)
    if organic_sessions:
        print(f"\n--- Session ranges ---", file=sys.stderr)
        print(f"  Organic: S{min(organic_sessions)}-S{max(organic_sessions)} (mean S{output['session_distribution']['organic_mean_session']}, median S{output['session_distribution']['organic_median_session']})", file=sys.stderr)
    if auto_sessions:
        print(f"  Auto:    S{min(auto_sessions)}-S{max(auto_sessions)} (mean S{output['session_distribution']['auto_mean_session']})", file=sys.stderr)
    print("", file=sys.stderr)

    # JSON to stdout
    print(json.dumps(output, indent=2, default=str))


if __name__ == "__main__":
    main()
